<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260118182422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE academic_year (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_275AE7215E237E06 ON academic_year (name)');
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, posted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scope VARCHAR(255) NOT NULL, author_id INT NOT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9474526CF675F31B ON comment (author_id)');
        $this->addSql('CREATE INDEX IDX_9474526C979B1AD6 ON comment (company_id)');
        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, vat_number VARCHAR(50) DEFAULT NULL, city VARCHAR(255) NOT NULL, exceptional_circumstances TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE company_liason (company_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (company_id, teacher_id))');
        $this->addSql('CREATE INDEX IDX_FA0B6293979B1AD6 ON company_liason (company_id)');
        $this->addSql('CREATE INDEX IDX_FA0B629341807E1D ON company_liason (teacher_id)');
        $this->addSql('CREATE TABLE educational_centre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE educational_centre_admins (educational_centre_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (educational_centre_id, user_id))');
        $this->addSql('CREATE INDEX IDX_9F1F12EF61F9EE23 ON educational_centre_admins (educational_centre_id)');
        $this->addSql('CREATE INDEX IDX_9F1F12EFA76ED395 ON educational_centre_admins (user_id)');
        $this->addSql('CREATE TABLE "group" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, details TEXT DEFAULT NULL, programme_year_id INT NOT NULL, tutor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DC044C59B62B32C ON "group" (programme_year_id)');
        $this->addSql('CREATE INDEX IDX_6DC044C5208F64F1 ON "group" (tutor_id)');
        $this->addSql('CREATE TABLE group_teacher (group_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (group_id, teacher_id))');
        $this->addSql('CREATE INDEX IDX_36F6F2D9FE54D947 ON group_teacher (group_id)');
        $this->addSql('CREATE INDEX IDX_36F6F2D941807E1D ON group_teacher (teacher_id)');
        $this->addSql('CREATE TABLE professional_family (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, academic_year_id INT NOT NULL, head_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5585387C54F3401 ON professional_family (academic_year_id)');
        $this->addSql('CREATE INDEX IDX_E5585387F41A619E ON professional_family (head_id)');
        $this->addSql('CREATE TABLE programme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, details TEXT DEFAULT NULL, professional_family_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3DDCB9FF761D1F81 ON programme (professional_family_id)');
        $this->addSql('CREATE TABLE programme_coordinator (programme_id INT NOT NULL, teacher_id INT NOT NULL, PRIMARY KEY (programme_id, teacher_id))');
        $this->addSql('CREATE INDEX IDX_C3CFC5B562BB7AEE ON programme_coordinator (programme_id)');
        $this->addSql('CREATE INDEX IDX_C3CFC5B541807E1D ON programme_coordinator (teacher_id)');
        $this->addSql('CREATE TABLE programme_year (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, details TEXT DEFAULT NULL, programme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2C2415A62BB7AEE ON programme_year (programme_id)');
        $this->addSql('CREATE TABLE student (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, student_id VARCHAR(50) NOT NULL, details VARCHAR(255) DEFAULT NULL, excluded BOOLEAN NOT NULL, group_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B723AF33FE54D947 ON student (group_id)');
        $this->addSql('CREATE TABLE teacher (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, user_id INT DEFAULT NULL, academic_year_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B0F6A6D5A76ED395 ON teacher (user_id)');
        $this->addSql('CREATE INDEX IDX_B0F6A6D5C54F3401 ON teacher (academic_year_id)');
        $this->addSql('CREATE TABLE training_position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, details TEXT DEFAULT NULL, signed BOOLEAN NOT NULL, state VARCHAR(255) NOT NULL, student_id INT DEFAULT NULL, academic_tutor_id INT DEFAULT NULL, workplace_mentor_id INT DEFAULT NULL, workcenter_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A149F762CB944F1A ON training_position (student_id)');
        $this->addSql('CREATE INDEX IDX_A149F7621FBFECE6 ON training_position (academic_tutor_id)');
        $this->addSql('CREATE INDEX IDX_A149F7625256CD7A ON training_position (workplace_mentor_id)');
        $this->addSql('CREATE INDEX IDX_A149F762A2473C4B ON training_position (workcenter_id)');
        $this->addSql('CREATE TABLE training_position_programme_year (training_position_id INT NOT NULL, programme_year_id INT NOT NULL, PRIMARY KEY (training_position_id, programme_year_id))');
        $this->addSql('CREATE INDEX IDX_41997DF479EF5491 ON training_position_programme_year (training_position_id)');
        $this->addSql('CREATE INDEX IDX_41997DF49B62B32C ON training_position_programme_year (programme_year_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, username VARCHAR(180) NOT NULL, external BOOLEAN NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE TABLE workcenter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(255) DEFAULT NULL, company_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E2337C97979B1AD6 ON workcenter (company_id)');
        $this->addSql('CREATE TABLE workcenter_worker (workcenter_id INT NOT NULL, worker_id INT NOT NULL, PRIMARY KEY (workcenter_id, worker_id))');
        $this->addSql('CREATE INDEX IDX_AAF9960CA2473C4B ON workcenter_worker (workcenter_id)');
        $this->addSql('CREATE INDEX IDX_AAF9960C6B20BA36 ON workcenter_worker (worker_id)');
        $this->addSql('CREATE TABLE worker (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, national_id_number VARCHAR(20) NOT NULL, work_email VARCHAR(255) DEFAULT NULL, work_phone_number VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9FB2BF628B718EB0 ON worker (national_id_number)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE company_liason ADD CONSTRAINT FK_FA0B6293979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_liason ADD CONSTRAINT FK_FA0B629341807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE educational_centre_admins ADD CONSTRAINT FK_9F1F12EF61F9EE23 FOREIGN KEY (educational_centre_id) REFERENCES educational_centre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE educational_centre_admins ADD CONSTRAINT FK_9F1F12EFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C59B62B32C FOREIGN KEY (programme_year_id) REFERENCES programme_year (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "group" ADD CONSTRAINT FK_6DC044C5208F64F1 FOREIGN KEY (tutor_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE group_teacher ADD CONSTRAINT FK_36F6F2D9FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE group_teacher ADD CONSTRAINT FK_36F6F2D941807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE professional_family ADD CONSTRAINT FK_E5585387C54F3401 FOREIGN KEY (academic_year_id) REFERENCES academic_year (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE professional_family ADD CONSTRAINT FK_E5585387F41A619E FOREIGN KEY (head_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE programme ADD CONSTRAINT FK_3DDCB9FF761D1F81 FOREIGN KEY (professional_family_id) REFERENCES professional_family (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE programme_coordinator ADD CONSTRAINT FK_C3CFC5B562BB7AEE FOREIGN KEY (programme_id) REFERENCES programme (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE programme_coordinator ADD CONSTRAINT FK_C3CFC5B541807E1D FOREIGN KEY (teacher_id) REFERENCES teacher (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE programme_year ADD CONSTRAINT FK_A2C2415A62BB7AEE FOREIGN KEY (programme_id) REFERENCES programme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE student ADD CONSTRAINT FK_B723AF33FE54D947 FOREIGN KEY (group_id) REFERENCES "group" (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE teacher ADD CONSTRAINT FK_B0F6A6D5C54F3401 FOREIGN KEY (academic_year_id) REFERENCES academic_year (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_position ADD CONSTRAINT FK_A149F762CB944F1A FOREIGN KEY (student_id) REFERENCES student (id)');
        $this->addSql('ALTER TABLE training_position ADD CONSTRAINT FK_A149F7621FBFECE6 FOREIGN KEY (academic_tutor_id) REFERENCES teacher (id)');
        $this->addSql('ALTER TABLE training_position ADD CONSTRAINT FK_A149F7625256CD7A FOREIGN KEY (workplace_mentor_id) REFERENCES worker (id)');
        $this->addSql('ALTER TABLE training_position ADD CONSTRAINT FK_A149F762A2473C4B FOREIGN KEY (workcenter_id) REFERENCES workcenter (id)');
        $this->addSql('ALTER TABLE training_position_programme_year ADD CONSTRAINT FK_41997DF479EF5491 FOREIGN KEY (training_position_id) REFERENCES training_position (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE training_position_programme_year ADD CONSTRAINT FK_41997DF49B62B32C FOREIGN KEY (programme_year_id) REFERENCES programme_year (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workcenter ADD CONSTRAINT FK_E2337C97979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workcenter_worker ADD CONSTRAINT FK_AAF9960CA2473C4B FOREIGN KEY (workcenter_id) REFERENCES workcenter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE workcenter_worker ADD CONSTRAINT FK_AAF9960C6B20BA36 FOREIGN KEY (worker_id) REFERENCES worker (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C979B1AD6');
        $this->addSql('ALTER TABLE company_liason DROP CONSTRAINT FK_FA0B6293979B1AD6');
        $this->addSql('ALTER TABLE company_liason DROP CONSTRAINT FK_FA0B629341807E1D');
        $this->addSql('ALTER TABLE educational_centre_admins DROP CONSTRAINT FK_9F1F12EF61F9EE23');
        $this->addSql('ALTER TABLE educational_centre_admins DROP CONSTRAINT FK_9F1F12EFA76ED395');
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C59B62B32C');
        $this->addSql('ALTER TABLE "group" DROP CONSTRAINT FK_6DC044C5208F64F1');
        $this->addSql('ALTER TABLE group_teacher DROP CONSTRAINT FK_36F6F2D9FE54D947');
        $this->addSql('ALTER TABLE group_teacher DROP CONSTRAINT FK_36F6F2D941807E1D');
        $this->addSql('ALTER TABLE professional_family DROP CONSTRAINT FK_E5585387C54F3401');
        $this->addSql('ALTER TABLE professional_family DROP CONSTRAINT FK_E5585387F41A619E');
        $this->addSql('ALTER TABLE programme DROP CONSTRAINT FK_3DDCB9FF761D1F81');
        $this->addSql('ALTER TABLE programme_coordinator DROP CONSTRAINT FK_C3CFC5B562BB7AEE');
        $this->addSql('ALTER TABLE programme_coordinator DROP CONSTRAINT FK_C3CFC5B541807E1D');
        $this->addSql('ALTER TABLE programme_year DROP CONSTRAINT FK_A2C2415A62BB7AEE');
        $this->addSql('ALTER TABLE student DROP CONSTRAINT FK_B723AF33FE54D947');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5A76ED395');
        $this->addSql('ALTER TABLE teacher DROP CONSTRAINT FK_B0F6A6D5C54F3401');
        $this->addSql('ALTER TABLE training_position DROP CONSTRAINT FK_A149F762CB944F1A');
        $this->addSql('ALTER TABLE training_position DROP CONSTRAINT FK_A149F7621FBFECE6');
        $this->addSql('ALTER TABLE training_position DROP CONSTRAINT FK_A149F7625256CD7A');
        $this->addSql('ALTER TABLE training_position DROP CONSTRAINT FK_A149F762A2473C4B');
        $this->addSql('ALTER TABLE training_position_programme_year DROP CONSTRAINT FK_41997DF479EF5491');
        $this->addSql('ALTER TABLE training_position_programme_year DROP CONSTRAINT FK_41997DF49B62B32C');
        $this->addSql('ALTER TABLE workcenter DROP CONSTRAINT FK_E2337C97979B1AD6');
        $this->addSql('ALTER TABLE workcenter_worker DROP CONSTRAINT FK_AAF9960CA2473C4B');
        $this->addSql('ALTER TABLE workcenter_worker DROP CONSTRAINT FK_AAF9960C6B20BA36');
        $this->addSql('DROP TABLE academic_year');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE company_liason');
        $this->addSql('DROP TABLE educational_centre');
        $this->addSql('DROP TABLE educational_centre_admins');
        $this->addSql('DROP TABLE "group"');
        $this->addSql('DROP TABLE group_teacher');
        $this->addSql('DROP TABLE professional_family');
        $this->addSql('DROP TABLE programme');
        $this->addSql('DROP TABLE programme_coordinator');
        $this->addSql('DROP TABLE programme_year');
        $this->addSql('DROP TABLE student');
        $this->addSql('DROP TABLE teacher');
        $this->addSql('DROP TABLE training_position');
        $this->addSql('DROP TABLE training_position_programme_year');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE workcenter');
        $this->addSql('DROP TABLE workcenter_worker');
        $this->addSql('DROP TABLE worker');
    }
}
