<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260118193254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_class VARCHAR(255) NOT NULL, entity_id VARCHAR(255) NOT NULL, action VARCHAR(50) NOT NULL, old_values JSON DEFAULT NULL, new_values JSON DEFAULT NULL, changed_fields JSON DEFAULT NULL, user_id INT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, ip_address VARCHAR(50) DEFAULT NULL, user_agent TEXT DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, context JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, signature VARCHAR(128) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX created_idx ON audit_log (created_at)');
        $this->addSql('CREATE INDEX user_action_date_idx ON audit_log (user_id, action, created_at)');
        $this->addSql('CREATE INDEX entity_date_idx ON audit_log (entity_class, entity_id, created_at)');
        $this->addSql('CREATE INDEX transaction_idx ON audit_log (transaction_hash)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE audit_log');
    }
}
