name: Tests

on:
  push:
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: intl, pdo_sqlite, mbstring, ctype, dom, iconv, libxml
          coverage: none

      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: composer-${{ hashFiles('composer.lock') }}
          restore-keys: composer-

      - name: Instalar dependencias
        run: composer install --prefer-dist --no-interaction

      - name: Ejecutar tests
        run: php bin/phpunit
